---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-external-nginx
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.6.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      ports:
        http: 80
        https: 443
        http-alt: 8080
        stun: 3478
      targetPorts:
        http: http
        https: https
        http-alt: http-alt
        stun: stun
      ingressClassResource:
        name: external-ingress
        default: false
        controllerValue: k8s.io/external-ingress
      ingressClassByName: true
      extraArgs:
        default-ssl-certificate: |-
          networking/kirstein-me-tls
    tcp:
      "8080": default/unifi:8080
    udp:
      "3478": default/unifi:3478