---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: jellyfin
      version: 0.6.1
      sourceRef:
        kind: HelmRepository
        name: media-servarr
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    application:
      config:
      # Network Options
      - filename: 'network.xml'
        contents: |
          <?xml version="1.0" encoding="utf-8"?>
          <NetworkConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <BaseUrl>/</BaseUrl>
            <HttpServerPortNumber>8096</HttpServerPortNumber>
            <EnableHttps>false</EnableHttps>
            <PublicPort>8096</PublicPort>
            <EnableRemoteAccess>true</EnableRemoteAccess>
          </NetworkConfiguration>
        mountPath: '/config/config/network.xml'
      urlBase: ''
    ingress:
      enabled: true
      className: external-ingress
      host: jellyfin.kirstein.me 
      annotations:
          external-dns.alpha.kubernetes.io/target: "home.kirstein.me"
    deployment:
      container:
        securityContext:
          fsGroup: 106
        volumeMounts:
        - name: 'config'
          mountPath: '/config'
        - name: 'media'
          mountPath: '/data/media'
        - name: 'hardware'
          mountPath: '/dev/dri'
      volumes:
        media:
          persistentVolumeClaim:
            claimName: media-data
        hardware:
          hostPath:
            path: /dev/dri
    podSecurityContext:
      privileged: true
    persistentVolumeClaims:
      jellyfin-config:
        storageClassName: "nfs-client"
