---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: jellyfin
      version: 0.4.0
      sourceRef:
        kind: HelmRepository
        name: media-servarr
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    application:
      urlBase: ''
    ingress:
      enabled: true
      className: internal-ingress
      host: jellyfin.int.kirstein.me 
    deployment:
      container:
        securityContext:
          fsGroup: 106
        volumeMounts:
        - name: 'config'
          mountPath: '/config'
        - name: 'media'
          mountPath: '/data/media'
        - name: 'hardware'
          mountPath: '/dev/dri'
      volumes:
        media:
          persistentVolumeClaim:
            claimName: media-data
        hardware:
          hostPath:
            path: /dev/dri
    podSecurityContext:
      privileged: true
    persistentVolumeClaims:
      jellyfin-config:
        storageClassName: "nfs-client"
