kind: Service
apiVersion: v1
metadata:
  name: opendtu
  labels:
    k8s-app: opendtu
spec:
  type: ExternalName
  externalName: opendtu.fritz.box
  ports:
  - name: metrics
    port: 80
    protocol: TCP
    targetPort: 80