---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app orca
  namespace: default
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      main:
        strategy: Recreate
        containers:
          main:
            image:
              repository: linuxserver/orcaslicer
              tag: 2.3.1
              pullPolicy: Always
            env:
              PUID: 1000
              PGID: 1000
              TZ: Etc/UTC
    service:
      main:
        controller: main
        ports:
          http:
            port: &port 3000