
---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: mosquitto
      version: 4.8.2
      sourceRef:
        kind: HelmRepository
        name: mosquitto
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    persistence:
        data:
          enabled: true
          storageClassName: nfs-client
          size: 100Mi
    service:
      type: LoadBalancer
      annotations:
        external-dns.alpha.kubernetes.io/hostname: mqtt2.nas01.kirstein.me