---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-victoria-metrics-stack
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-nfs-subdir-external-provisioner
  path: ./kubernetes/apps/monitoring/victoria-metrics-stack/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: victoria-metrics-stack
      namespace: monitoring
  interval: 30m
  retryInterval: 1m
  timeout: 5ms
---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-victoria-metrics-stack-datasource
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-victoria-metrics-stack
  path: ./kubernetes/apps/monitoring/victoria-metrics-stack/datasource
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: victoria-metrics-stack
      namespace: monitoring
  interval: 30m
  retryInterval: 1m
  timeout: 5ms