---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1l6hn6tqssp82508dcmyrg0dcxrzjv04m0xc7apcffly02y9prqlsj3zmt2
  - path_regex: kubernetes/.*\.sops\.ini
    key_groups:
      - age:
          - age1l6hn6tqssp82508dcmyrg0dcxrzjv04m0xc7apcffly02y9prqlsj3zmt2
  - path_regex: kubernetes/.*\.sops\.toml
    key_groups:
      - age:
          - age1l6hn6tqssp82508dcmyrg0dcxrzjv04m0xc7apcffly02y9prqlsj3zmt2
  - path_regex: kubernetes/.*\.sops\.json
    key_groups:
      - age:
          - age1l6hn6tqssp82508dcmyrg0dcxrzjv04m0xc7apcffly02y9prqlsj3zmt2
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1l6hn6tqssp82508dcmyrg0dcxrzjv04m0xc7apcffly02y9prqlsj3zmt2
  - path_regex: terraform/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1l6hn6tqssp82508dcmyrg0dcxrzjv04m0xc7apcffly02y9prqlsj3zmt2