---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: teslamate-database
  namespace: default
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi
    storageClass: nfs-client
  postgresql:
    pg_hba:
      - hostssl app app 192.168.178.0/24 md5
  monitoring:
    enablePodMonitor: true
