---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./database.yaml
  - ./scheduledbackup.yaml
  - ./teslamate-backup.sops.yaml
labels:
  - pairs:
      app.kubernetes.io/name: teslamate-database
      app.kubernetes.io/instance: teslamate-database
      app.kubernetes.io/part-of: teslamate