---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/scheduledbackup_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: teslamate-database
  namespace: default
spec:
  schedule: "@midnight"
  immediate: true
  backupOwnerReference: self
  cluster:
    name: teslamate-database