---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: teslamate
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: teslamate
      version: 7.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      tag: 1.30.1
    env:
      - name: DATABASE_HOST
        value: teslamate-database-rw
      - name: DATABASE_USER
        valueFrom:
          secretKeyRef:
            name: teslamate-database-app
            key: username
      - name: DATABASE_PASS
        valueFrom:
          secretKeyRef:
            name: teslamate-database-app
            key: password
      - name: ENCRYPTION_KEY
        valueFrom:
          secretKeyRef:
            name: teslamate-encryption
            key: key
      - name: DATABASE_NAME
        value: app
      - name: DISABLE_MQTT
        value: true
    ingress:
      main:
        enabled: true
        ingressClassName: "internal-ingress"
        annotations: 
          external-dns.alpha.kubernetes.io/hostname: tesla.nas01.kirstein.me
        hosts:
          - host: tesla.nas01.kirstein.me
            paths:
            - path: /
              pathType: Prefix