---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: teslamate
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: teslamate
      version: 7.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      tag: 1.27.1
    env:
      - name: DATABASE_HOST
        value: teslamate-database-1
      - name: DATABASE_USER
        valueFrom:
          secretRef:
            name: teslamate-database-app
            key: username
      - name: DATABASE_PASS
        valueFrom:
          secretRef:
            name: teslamate-database-app
            key: password
      - name: DATABASE_PASS
        value: teslamate
      - name: DISABLE_MQTT
        value: true