
---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization
namespace: default
resources:
  - ./helmrelease.yaml
  - ./teslamate-encryption.sops.yaml
generatorOptions:
  disableNameSuffixHash: true
labels:
  - pairs:
      app.kubernetes.io/name: teslamate
      app.kubernetes.io/instance: teslamate
      app.kubernetes.io/part-of: teslamate