apiVersion: v1
kind: Secret
metadata:
    name: smtp-relay-secret
type: Opaque
stringData:
    SMTP_RELAY_SERVER: ENC[AES256_GCM,data:PQl6cGuWzLB4TQnRkf7a1g==,iv:7t+N+ZdUsQrGXLpx0q6Bf45NtisG6GhHSw0W41fIUXw=,tag:DaeSVvWjPZDaivsSy8QeZw==,type:str]
    SMTP_RELAY_USERNAME: ENC[AES256_GCM,data:DMxAwkvERpYpKrnGnFsTfjR/HpOV0+EyUZri,iv:bTEn1+E8k2ErTRRybQw7b4S/ifOemtY0hN6ecuiPEE0=,tag:Ec8wnQzOA1XKNILro5pTJQ==,type:str]
    SMTP_RELAY_PASSWORD: ENC[AES256_GCM,data:U52oD45UMaeZntxektlAPlmeLTEWiEwO1aVpX5udL6RL+k5StyvdVg==,iv:iYToaNmmJjdpTsuf+SvdTk6imzJm90aXLGLVSa2a1kg=,tag:9eic/AX0mPXd62UzMmPfXQ==,type:str]
sops:
    age:
        - recipient: age1l6hn6tqssp82508dcmyrg0dcxrzjv04m0xc7apcffly02y9prqlsj3zmt2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmTUwzcS80N3R0QjJwZzRt
            WlVkQmlVOTJKejFIeU05NjZIUlkzaXl0L0UwCmNqNU51dXZzOUpPMy8xQVU2ekF6
            U3dhMFRWQlZUWXNyMDJhZTZJQXdYd1EKLS0tIGZSL1ZZcU9Jbi95RUpVWjdkT1RO
            Q1BaNXJwVUthclJXQ3ZONVM4ZDJ0ODAK/Ywewx7jVTww6Zc9VVFMNpYhfShYW4mm
            qDGaxVVobNURQoQKEOl7Y80dEN1d3kICR4XBCOb8J1U1/RiMaeKM6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T12:15:29Z"
    mac: ENC[AES256_GCM,data:JBAlL7kFIR46JxlIjxUNinm6LEcB9v+vN8Bk5FmKGQrW8/F+/cVcL9aTLQI4xRz4vrXa92QRjFqzpgF1hX1n3RpWWIS1zbCBiIoWF3QLK4rU1C2aPqicw+1Gv/SKqhRKmCBrZ/xbxsnBp5ts6n5KojOKqKUBaUcsqEos0YrsIJ8=,iv:1Dl2sJnPFCGxdiSBWgFEMJ6BBWZvzBYJ7yEQtWn4eok=,tag:h8VAbGb3D+HuAtQpsx6Nhw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
