---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app zigbee2mqtt
  namespace: default
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: zigbee2mqtt
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      *app :
        type: deployment
        replicas: 1
        containers:
          main:
            image: 
              repository: ghcr.io/koenkk/zigbee2mqtt
              tag: 2.8.0@sha256:89cf02f379aa743a68494388e3a26fba7b8c9101f8b452038cc07aeff3fc983c
            resources:
              requests:
                cpu: 15m
                memory: 150Mi
              limits:
                memory: 150Mi
            securityContext:
              privileged: true
            probes:
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
              liveness:
                enabled: true
              readiness:
                enabled: true
            env:
              ZIGBEE2MQTT_DATA: /data
              ZIGBEE2MQTT_CONFIG_HOMEASSISTANT_ENABLED: true
              ZIGBEE2MQTT_CONFIG_HOMEASSISTANT_DISCOVERY_TOPIC: homeassistant
              ZIGBEE2MQTT_CONFIG_HOMEASSISTANT_STATUS_TOPIC: homeassistant/status
              # mqtt
              ZIGBEE2MQTT_CONFIG_MQTT_SERVER: mqtt://mosquitto
              ZIGBEE2MQTT_CONFIG_MQTT_INCLUDE_DEVICE_INFORMATION: "true"
              ZIGBEE2MQTT_CONFIG_MQTT_VERSION: "5"
              
              # adapter
              ZIGBEE2MQTT_CONFIG_SERIAL_PORT: &usbdevice /dev/ttyACM0
              ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER: deconz
    service:
      zigbee2mqtt:
        controller: *app
        ports:
          http:
            port: 8080
            protocol: HTTP
            appProtocol: http
    serviceMonitor:
      app:
        serviceName: *app
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s
    persistence:
      data:
        enabled: true
        storageClass:  nfs-client
        accessMode: ReadWriteOnce
        size: 1Gi
      usb:
        type: hostPath
        hostPath: *usbdevice
        hostPathType: CharDevice
        globalMounts:
          - path: *usbdevice
    securityContext:
      privileged: true
    ingress:
      main:
        enabled: true
        className: "internal-ingress"
        annotations: 
          external-dns.alpha.kubernetes.io/hostname: z2m.nas01.kirstein.me
        hosts:
          - host: "z2m.nas01.kirstein.me"
            paths:
              - path: /
                pathType: Prefix