apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: grafana
  namespace: monitoring
spec:
  deployment:
    replicas: 1
    envFrom:
      - secretRef:
          name: grafana-secrets
      - secretRef:
          name: grafana-env
  client:
    preferService: true
  ingress:
    enabled: True
    ingressClassName: external-ingress
    hostname: grafana.kirstein.me
    path: /
    pathType: Prefix
    annotations: 
      external-dns.alpha.kubernetes.io/hostname: grafana.kirstein.me
      external-dns.alpha.kubernetes.io/target: home.kirstein.me
  config:
    alerting:
      enabled: false
    unified_alerting:
      enabled: false
    auth: 
      signout_redirect_url: https://auth.kirstein.me/application/o/grafana/end-session/
      oauth_auto_login: true
    auth.generic_oauth:
      name: authentik
      enabled: true
      scopes: openid email profile
      auth_url: https://auth.kirstein.me/application/o/authorize/
      token_url: https://auth.kirstein.me/application/o/token/
      api_url: https://auth.kirstein.me/application/o/userinfo/
      role_attribute_path: contains(groups[*], 'Grafana Admins') && 'Admin' || contains(groups[*], 'Grafana Editors') && 'Editor' || 'Viewer'
    log:
      mode: "console"
      level: "error"
    log.frontend:
      enabled: true
    server:
      domain: grafana.kirstein.me
      root_url: "https://%(domain)s"
  dashboardLabelSelector:
    - matchExpressions:
        - { key: app, operator: In, values: [grafana] }
  resources:
    # Optionally specify container resources
    limits:
      cpu: 50Mi
      memory: 200Mi
    requests:
      cpu: 50Mi
      memory: 100Mi