apiVersion: v1
kind: Secret
metadata:
    name: grafana-secrets
    namespace: monitoring
type: Opaque
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:lH80cybZbA==,iv:F5VzorGmXl2B5myHrZRUaqZDIqCYUCOwO9TN1Y2jUqs=,tag:mJ69ZW+e9sxM8lH8VKG2Ow==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:7+U1Q9U/kUT36pWzAnpMw1XoTPcvJIfTs5GdC2euUdM/FGbQPGdftNhpwpNV0PTGlMtefgBd6CM11w4Mjkj2tLdyuDurPp7pMn0b00D4iaGSPv5RFsZ8L7fw7Xa4+ZU0NyU8Mj/5JrwY/Sh0N9Wz19/OQNhK2iFYs/H4R2T8kFk=,iv:2Q2GNvNQsTr+6/XHm4nNZng3mCNI0uu69M/UFqtMUPU=,tag:HNwd9LEpTpVwNkyKfWG2vQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l6hn6tqssp82508dcmyrg0dcxrzjv04m0xc7apcffly02y9prqlsj3zmt2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRcDI4TGNCNiswU01nVHd0
            RnpyYUh6NmhyOGd6Ynp0SVdyTExCUmJtbml3CnAyUGQ1QVN2cTc0UW01RFE3WkVj
            U0QrN3VuWnJpTExLWDA1MEpod2NNcjQKLS0tIHY2R2RDdG1MYjB5VjBuWHl6aXBH
            aHo5eHBwQXQ4aXR5TDhuSUplRDdrbmcKCH/kiEMGmAedJMYB1McI+1S8oB04f2Cm
            x9ba6ltwZcSTy/ekNAG448xF35BujMuU0ad3rePo6XpvbJ1cAjtS9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-12T15:41:30Z"
    mac: ENC[AES256_GCM,data:DPhcS0VS8JeeQsNW+893t+1oQ9dZuj7IAhIi/LXi3veH2ocuTZmCkdWYLeo+3ctjMqx/eQ8bA3fHnxa9kVBI94A6Ppv/30MX8RHlfcoanCR5ELSgT7Ulb7n/ZMtszij4AySS3nw+vPbuFpJVpZ7dmNaxmUS/TJPyRuWmRLF3/QY=,iv:+5eHPDKNCHdFVEbJKECN7m/RPYzTwshTm4jUWf3T46o=,tag:vMDj+EpJ6B6zYIfLw1LnmA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
