apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: ahoydtu
  name: ahoydtu
  namespace: monitoring
spec:
  endpoints:
  - path: /metrics
    interval: 30s
    targetPort: 80
    scheme: http
  namespaceSelector:
    matchNames:
    - default
  selector:
    app: gopher-builder