apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: ahoydtu
  name: ahoydtu
spec:
  endpoints:
  - path: /metrics
    interval: 30s
    targetPort: 80
    scheme: http
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      k8s-app: ahoydtu