apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: ahoydtu
  name: ahoydtu
spec:
  endpoints:
  - path: /metrics
    interval: 30s
    port: metrics
    scheme: http
    relabelings:
      - sourceLabels: [__address__]
        targetLabel: __address__
        regex: (.*)
        replacement: "ahoydtu.fritz.box"
        action: replace
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      k8s-app: ahoydtu