---
apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  namespace: monitoring
  name: prometheus-datasource
spec:
  name: Prometheus
  datasources:
  - name: prometheus
    type: prometheus
    url: https://vm.nas01.kirstein.me