---
apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  namespace: monitoring
  name: teslamate-datasource
spec:
  name: TeslaMate
  datasources:
  - name: prometheus
    type: prometheus
    url: https://vm.nas01.kirstein.me
  - name: TeslaMate
    type: postgres
    database: app
    editable: false
    jsonData:
      connMaxLifetime: 14400
      maxIdleConns: 2
      maxOpenConns: 0
      postgresVersion: 1400
      sslmode: disable
      timescaledb: false
    secureJsonData:
      password: ${SECRET_TESLAMATE_POSTGRES_PASSWORD}
    url: 192.168.178.204:5432
    user: app
  plugins:
      - name: fetzerch-sunandmoon-datasource
        version: 0.3.0