
---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: emqx
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: emqx
      version: 5.0.16
      sourceRef:
        kind: HelmRepository
        name: emqx
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: public.ecr.aws/emqx/emqx
    replicaCount: 1
    recreatePods: true
    persistence:
      enabled: true
      storageClassName: nfs-client
      size: 100Mi
    ingress:
      enabled: true
      annotations:
        external-dns.alpha.kubernetes.io/hostname: &host mqtt.nas01.kirstein.me
      ingressClassName: "internal-ingress"
      path: /
      pathType: Prefix
      hosts:
        - *host