apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
    namespace: default
type: Opaque
stringData:
    key: ENC[AES256_GCM,data:ogqQu5pOOoRLmV1VRL0fxZhTq9B3YBqXj1yoikHmmcnIlv2YUVQezToYy7jsSoalgbz8uGmV756C450C7jHj8w==,iv:Ly4xlerKmMdsGHREwGxi3jLRXNH71sdObvhdyJllT+U=,tag:mdWJ0aEYlF+FbWcTcjzCWw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l6hn6tqssp82508dcmyrg0dcxrzjv04m0xc7apcffly02y9prqlsj3zmt2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIWmMyNGowRWs3d3dUWVBu
            ajVEZUFyVURITncyK1MwVXNXMXRMU2lRZFNVCjRoS3pkUWlKU1pTc0hhVzNMeXVS
            dFQxeVI2MTVXNUFtMUxDVkNKT0VYcUEKLS0tIFhoVjdIKytDdGZtRDNvckdncy9s
            TmVTeXdqTklPL2dsWXRZcVVpMjFheFkK403M0zBzBbj/8403MDVEtO70cs/gJzjt
            GtYJSqC+erKOhWV5Dws3S+S6WIp2zLPHQpmPZ3Nj6FILUgIP2F6PHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-20T10:03:27Z"
    mac: ENC[AES256_GCM,data:/2px9Ixs+R3pRKRQpIu8dtG2FEHCrOhtvNqaRyjHqBpM71Fa/jLPoRT3a1sODSGZd5uL9h+O3vRRaTWg9aI3PU0ivVfY+iKbFxooyGHSIskr5u3TpoJgZN5cP7AhQA88oQfOyHnXa/CnVor5DMzlaGAsSc2VcTh3O2Gxd2pxWCE=,iv:T7m7fi/X0zqUIQx4UogM1NbrnfCEPBemBQ8GB0Mf5Ac=,tag:0WfuQRyOlFhsfJN7HFM+Hw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
