apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
spec:
  interval: 1h
  chart:
    spec:
      chart: authentik
      version: 2023.3.1
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/goauthentik/server
      tag: 2023.3.1
    replicas: 1
    geoip:
      enabled: false
    postgresql:
      enabled: false
    redis:
      enabled: false
    envValueFrom:
      AUTHENTIK_SECRET_KEY:
        secretKeyRef:
          name: authentik-secret
          key: key
      AUTHENTIK_POSTGRESQL__USER: 
        secretKeyRef:
            name: authentik-database-app
            key: username
      AUTHENTIK_POSTGRESQL__PASSWORD:
        secretKeyRef:
            name: authentik-database-app
            key: password
    ingress:
      enabled: true
      ingressClassName: external-ingress
      annotations:
        external-dns.alpha.kubernetes.io/target: "home.kirstein.me"
      hosts:
        - host: &host "auth.kirstein.me"
          paths:
            - path: "/"
              pathType: Prefix
      tls:
        - hosts:
            - *host
    prometheus:
      rules:
        create: true
      serviceMonitor:
        create: true

    # Unset default values
    authentik:
      postgresql:
        host: authentik-database-rw
        name: app
        user: null
        password: null
      redis:
        host: authentik-redis-master