---
kubernetes:
  children:
    master:
      vars:
        ansible_user: root
        ansible_ssh_port: 22
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
      hosts:
        nas01:
          ansbile_host: 192.168.178.200