apiVersion: v1
kind: Secret
metadata:
    name: external-dns-internal-unifi-secret
    namespace: networking
stringData:
    username: ENC[AES256_GCM,data:Q/eJ7E1w3mNv3BY=,iv:1ExqYs9zbh2cCPF1ra/3QxPzMAnxE+glyMJCn9m19FU=,tag:/YSDFw6fzswRBQAf9LE3tA==,type:str]
    password: ENC[AES256_GCM,data:1FYADuV6dDu/y0phdnWqmlmDkt8=,iv:6hky20NZCJlQ0rp52x6Vi99aM7oypIM1UvB4yoG3RUM=,tag:1NYzrdkQg1ClLj+EY9SQtA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l6hn6tqssp82508dcmyrg0dcxrzjv04m0xc7apcffly02y9prqlsj3zmt2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMGxWTFJ4bFZ3cXRXL25H
            b29OWjAvNy9SYjhzRm5QL3psdXBtYmdWSEZJCkpiK1d1VFR6Y2hkSHdkU1o3STRV
            VTZxNkZiNWlyVCtyeFNUbUJOeWg0eEUKLS0tIGwzZDErb2tMWDFwTHZDNy9iTjNR
            OVBxWGdPWlBaalBWTUpyejZSTzl4c3cKgPu3+pqZbYg9lLO4HytcWIY+OxoBDWmb
            x81dWcenW2rtjWlQT8CG2bPgMR2U8W3+iSEFMKuJxI/Va9Te2OBRcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-10T18:16:33Z"
    mac: ENC[AES256_GCM,data:tUVNYiE2IK3lX0PJASxOcmmNqpSUbWGT6MX7PGTonpvCUphCXaxDkk55/DmWrSFcJmS7j5kD2IMWROZ7110SQZv63lmVZV6pBcbut32ZJleEQgdusUtjrccGW1+Ar8o82pcFdfVmMs1PcaMMMvstwH4xRZ2vlKwSgvrqS9Y29nI=,iv:U4+PaEXZpkWWLmA+8u4XLAfPP1a41Nm9QWm0NvpvuOg=,tag:AT/HChG9zY7oZvDDNVifSQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
