---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: actualbudget
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: actualbudget
      version: 1.8.2
      sourceRef:
        kind: HelmRepository
        name: community-charts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    extraEnvVars:
      ACTUAL_OPENID_SERVER_HOSTNAME: 'https://actual.kirstein.me'
    ingress:
      enabled: true
      className: external-ingress
      annotations:
          external-dns.alpha.kubernetes.io/target: "home.kirstein.me"
      hosts:
        - host: &host actual.kirstein.me
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts: 
          - *host
    persistence:
      enabled: true
      storageClass: nfs-client
    login:
      method: "openid"
      openid:
        enforce: true
        providerName: "Authelia"
        discoveryUrl: "https://auth.kirstein.me/.well-known/openid-configuration"
        tokenExpiration: "openid-provider"
        existingSecret:
          name: "actualbudget"
          clientIdKey: "clientId"
          clientSecretKey: "clientSecret"
