---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unifi
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: unifi
      version: 5.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: jacobalberty/unifi
      tag: v9.0.114
    service:
      main: 
        type: LoadBalancer
    persistence:
      data:
        enabled: true
        storageClass:  nfs-client
        accessMode: ReadWriteOnce
        size: 1Gi
    ingress:
      main:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/proxy-body-size: 50m
          external-dns.alpha.kubernetes.io/target: home.kirstein.me
        ingressClassName: "external-ingress"
        hosts:
          - host: unifi.kirstein.me
            paths:
            - path: /
              pathType: Prefix
              service:
                name: unifi
                port: 8443