---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./actualbudget/ks.yaml
  - ./authelia/ks.yaml
  - ./cloudnative-pg/ks.yaml
  - ./home-assistant/ks.yaml
  - ./homebridge/ks.yaml
  - ./jellyfin/ks.yaml
  - ./jellyseerr/ks.yaml
  - ./lldap/ks.yaml
  - ./mosquitto/ks.yaml
  - ./opendtu/ks.yaml
  - ./orca/ks.yaml
  - ./paperless/ks.yaml
  - ./teslamate/ks.yaml
  - ./radarr/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./sonarr/ks.yaml
  - ./unifi/ks.yaml
  - ./zigbee2mqtt/ks.yaml
