---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./cloudnative-pg/ks.yaml
  - ./emqx/ks.yaml
  - ./homebridge/ks.yaml
  - ./mqtt-exporter/ks.yaml
  - ./teslamate/ks.yaml
  - ./unifi/ks.yaml
  - ./zigbee2mqtt/ks.yaml
