---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: agones
  namespace: agones-system
spec:
  interval: 15m
  chart:
    spec:
      chart: agones
      version: 1.42.0
      sourceRef:
        kind: HelmRepository
        name: agones
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    agones:
      featureGates: "PlayerTracking=true"
      metrics:
        serviceMonitor:
          enabled: true
      controller:
        replicas: 1 
      ping:
        install: false
      allocator:
        install: false
      extensions:
        replicas: 1
    gameservers:
      namespaces:
        - "gameserver"