apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization
resources:
- gameserver.yaml
- cm.yaml
- pvc.yaml
labels:
  - pairs:
      app.kubernetes.io/name: factorio
      app.kubernetes.io/instance: factorio
      app.kubernetes.io/part-of: factorio