
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kirstein-me
  namespace: networking
spec:
  secretName: kirstein-me-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: kirstein.me
  dnsNames:
    - kirstein.me
    - "*.kirstein.me"