---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
namePrefix: grafana-operator-
resources:
  - github.com/grafana-operator/grafana-operator/tree/8bed473923b59388228d19dc2836a5f7e25b9344/deploy/manifests/v4.10.0
patchesStrategicMerge:
- security_context.yaml
