---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - helmrelease.yaml
labels:
  - pairs:
      app.kubernetes.io/name: open-thread
      app.kubernetes.io/instance: open-thread
      app.kubernetes.io/part-of: open-thread