---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tibber-exporter
spec:
  interval: 15m
  chart:
    spec:
      chart: tibber-exporter
      version: 1.8.1
      sourceRef:
        kind: HelmRepository
        name: tibber-exporter
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    tibberToken: ${SECRET_TIBBER_TOKEN}
    serviceMonitor:
      enabled: true