apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ALERTMANAGER_STATUSCAKE_URL: ENC[AES256_GCM,data:ZB+Mlz9/kYwFgzEIlaV0rFjcp7Mfprm6XfrCyjstB+3YqspEXmgoZFw=,iv:aRxlbuXd6psskrCdHXg0gv9cz06pF9lWDH2v3VJFjG0=,tag:T6EgWGF52/g9h1prwfBYDQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l6hn6tqssp82508dcmyrg0dcxrzjv04m0xc7apcffly02y9prqlsj3zmt2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCWkZtRmVUZGhVL01qcmt0
            L0Z5cVdrWkNMMUMyaEdLb21WRUpNSEQ3S1I0CjgyaFZHY1poRnlMeThyUElWYU9s
            L25BeVRTQTZiR25ST0pHQ1VlZTZDNzAKLS0tIFF6UkZSeFJlMU9uckNmSzc3SXZx
            dkxoMDJqem03Z2RkSURsZjJubDlaYW8KgqtdmaQ1IxpIH7kwCCLyjr4nk6rSkxTw
            Ibnydit6ixjuE81Rqc14uXAiUzOlFM6JVNfBWPN0LSxWDiiuvlQ+8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-08T09:02:04Z"
    mac: ENC[AES256_GCM,data:N8FY1e7+inQ6kf91yVVUrPsTarJK6YJbeYqH7vpWN8wwmjxvEYJB8k1IPUQ7o5YtNMHA9JaDp7UjB1onRq2OD2Qs8VgaJczdH+50+k1weRc8n1GhUOnmk6KY+EM3B9msNvJwzGbiYROzHsmvFMi/4cFmAW4wfVTBSYzipMuaTFA=,iv:P5BcNApfCxV24Pf0sv3nio8cFzE/FT/NeFhBXowyS5w=,tag:3kc4XjMG/pNWpWeAzSQ4ZA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
