---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./external-dns/ks.yaml
  - ./holepunch/ks.yaml
  - ./ingress-nginx/ks.yaml
  - ./metallb/ks.yaml