---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app zigbee2mqtt-exporter
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: docker.io/kpetrem/mqtt-exporter
      tag: latest@sha256:aa89ed7482d6801c70fb00ed32b7642243c057fbda6e53542f941a0634a1a75b
    env:
      LOG_LEVEL: DEBUG
      LOG_MQTT_MESSAGE: "True"
      MQTT_ADDRESS: mosquitto
      MQTT_TOPIC: "zigbee2mqtt/#"
      MQTT_V5_PROTOCOL: "True"
      PROMETHEUS_PORT: &port 8080
      PROMETHEUS_PREFIX: zigbee2mqtt_
      ZIGBEE2MQTT_AVAILABILITY: "True"
    service:
      main:
        ports:
          http:
            port: *port
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        memory: 200Mi