---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./helmrelease.yaml
  - ./servicescrape.yaml
labels:
  - pairs:
      app.kubernetes.io/name: zigbee2mqtt-exporter
      app.kubernetes.io/instance: zigbee2mqtt-exporter
      app.kubernetes.io/part-of: zigbee2mqtt