apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: zigbee2mqtt-exporter
spec:
  endpoints:
  - path: /
    interval: 30s
    port: http
    scheme: http
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app.kubernetes.io/name: zigbee2mqtt-exporter