apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: zigbee2mqtt-exporter
  name: zigbee2mqtt-exporter
spec:
  endpoints:
  - path: /
    interval: 30s
    port: metrics
    scheme: http
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      k8s-app: zigbee2mqtt-exporter