apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: zigbee2mqtt-exporter
spec:
  endpoints:
  - port: http
    path: ''
  selector:
    matchLabels:
      app.kubernetes.io/name: zigbee2mqtt-exporter