---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./endpoints.yaml
  - ./service.yaml
  - ./servicemonitor.yaml
labels:
  - pairs:
      app.kubernetes.io/name: ahoydtu-parents
      app.kubernetes.io/instance: ahoydtu-parents
      app.kubernetes.io/part-of: ahoydtu-parents