---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: sonarr
      version: 0.6.0
      sourceRef:
        kind: HelmRepository
        name: media-servarr
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    persistentVolumeClaims:
      sonarr-config:
        storageClassName: "nfs-client"
      downloads:
        storageClassName: "nfs-data"
      tv:
        storageClassName: "nfs-data"
