---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-teslamate
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-teslamate-database
  path: ./kubernetes/apps/default/teslamate/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: teslamate
      namespace: default
  patches:
    - patch: |
        - op: add
          path: /spec/template/spec/containers/0/env/-
          value:
            name: DATABASE_USER
            valueFrom:
              secretRef:
                name: teslamate-database-app
        - op: add
          path: /spec/template/spec/containers/0/env/-
          value:
            name: DATABASE_PASS
            valueFrom:
              secretRef:
                name: teslamate-database-app
                key: password
      target: 
        kind: Deployment
        name: teslamate
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-teslamate-database
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-cloudnative-pg
    - name: cluster-apps-nfs-subdir-external-provisioner
  path: ./kubernetes/apps/default/teslamate/database
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m