---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: paperless
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/paperless-ngx/paperless-ngx
      tag: 1.13.0
    env:
      - name: COMPOSE_PROJECT_NAME
        value: paperless-ngx
      - name: PAPERLESS_TIME_ZONE
        value: Europe/Berlin
      - name: PAPERLESS_URL
        value: http{{if ne ( len .Values.ingress.main.tls ) 0 }}s{{end}}://{{ (first .Values.ingress.main.hosts).host }}
      - name: PAPERLESS_DBHOST
        value: paperless-database-rw
      - name: PAPERLESS_DBNAME
        value: app
      - name: PAPERLESS_DBUSER
        valueFrom:
          secretKeyRef:
            name: paperless-database-app
            key: username
      - name: PAPERLESS_DBPASS
        valueFrom:
          secretKeyRef:
            name: paperless-database-app
            key: password
      - name: PAPERLESS_REDIS
        value: redis://paperless-redis-master:6379
      - name: USERMAP_UID
        value: 33
      - name: USERMAP_GID
        value: 33
      - name: PAPERLESS_CONSUMPTION_DIR
        value: /paperless/consume
      - name: PAPERLESS_DATA_DIR
        value: /paperless/data
      - name: PAPERLESS_MEDIA_ROOT
        value: /paperless/media
      - name: PAPERLESS_FILENAME_FORMAT
        value: "{created_year}/{correspondent}/{title}"
      - name: PAPERLESS_FILENAME_FORMAT_REMOVE_NONE
        value: true
      - name: PAPERLESS_CONSUMER_POLLING
        value: 60
      - name: PAPERLESS_CONSUMER_DELETE_DUPLICATES
        value: true
      - name: PAPERLESS_CONSUMER_RECURSIVE
        value: true
      - name: PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS
        value: true
      - name: PAPERLESS_OCR_LANGUAGE
        value: deu+eng
      - name: PAPERLESS_SECRET_KEY
       valueFrom:
          secretKeyRef:
            name: paperless-encryption
            key: key
    service:
      main:
        ports:
          http:
            port: 8000
    persistence:
      data:
        enabled: true
        mountPath: /paperless
        storageClass: nfs-client
        accessMode: ReadWriteOnce
        size: 10Gi
