apiVersion: v1
kind: Secret
metadata:
    name: paperless-encryption
    namespace: default
type: Opaque
stringData:
    key: ENC[AES256_GCM,data:TCiHnBt/0umZIeimUnhCFNsBQ3RK2CzGFsqIhNS+uHEZ5THF7DyZODKGjLA0ce8XDnEET0T0tvIapmPjGYmp+g==,iv:gXXH4yZUsbPqDcuK50jXjjkpCsh9o3m+rX3qyVNC3Pg=,tag:O91IopAPJ4G6SI2a69UDUQ==,type:str]
    username: ENC[AES256_GCM,data:BbC1DgQ=,iv:m0rqhNGPyM1XkjS3ixMZKTTte4nSedkV4nhYukjSTsE=,tag:mS6ZjWUEiUIMOJS+hfoTJw==,type:str]
    password: ENC[AES256_GCM,data:hv780duiAo2WzECBL0JzSrWhUhU=,iv:giYxoCljZA0ywE+Xk4zFeYreIkGInuvk6zZuNFmnEG8=,tag:GjINhS6k41JXtDg2vTWOYA==,type:str]
    paperless_socialaccount_providers: ENC[AES256_GCM,data:gRdTpt2AOoQ9DPTdoFMd6cWFee3ozqUtSuC+MEMQVFAXQArSkp2TflxswsdXXkAFqVQRolzGiGRh5c9yqz/P6xM44yyjn7WjVeMzBfbkNewr6N7BEs+BbeH0pLVlgVb9iO53qn5zKBQawrqDxIl4BDj0ow4Ou2QRg9kAvtbgTdhrJVs9GB45JW8XqnzuinAhRWbqKFHV5XBIalDVLyeg4lSu4kFFx3sCRYUpBf1w39Pxyzf2evPIvo8Nw2/SzT29gPdK+megPGFDrdRPW18rmChAmzKdSI77aOL5pfR1CvgiskNoiazwaabdGA+5bjdtHz+YyvU8wX0Z419gBCgcCrAxtHlgVNbuebGu8xJoF937FxZLfcb05wdqDMryj6SsmOKrrmYLZlQfk4VVZaEO3xTMBGv/NNADtwrYVQkrnngW3vHRGM49ljuXVp+y0oFd1vALHtzQGhcmtTsibYHGp4rJojo/mTxMYI2osC3FPTGZrDLiSOcxNO3mN5Ei,iv:fh+fubYf6RIAwl5whpJ4SxSJcHoUaHroFPgsFO5kCOs=,tag:l2Z+/R3v0h6coZ8xxkeDAg==,type:str]
sops:
    age:
        - recipient: age1l6hn6tqssp82508dcmyrg0dcxrzjv04m0xc7apcffly02y9prqlsj3zmt2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJRm5veU12TGlHUGZUN2ZZ
            emE4d05DM2VwUmp0b3VIMHBzdXE5MGQ3RGh3CitqNkVoM2Y1S1poZEdSczBvRkFU
            K1UxTjNKQjdDRXFXcUw0Nm05VG91L2sKLS0tIEVYczlBbkhGWTVpMzlUenBCYVJ2
            OFdqRllsYUxpS2V6bjNyMTJJMWRTdTAKCdk+0Cn15ZLNDnA9AFymfUKTb7wulLAs
            r7RRufZDerrP4/BNJ6yLLiuSRroNYk0B1FJhz64Elx39xY12D4pLfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T08:29:53Z"
    mac: ENC[AES256_GCM,data:xfSp0IqWPoj5SAIDiWIN6j9PvAHIhQNQ8LBwDX4M1KR6XASsg4Z/tfJm09K3EI47IXIVL5KSjgneHKvwIo+teOdEPt0FghsTBnFDEH7eNytaaMeG2oeS82nYZM9HX562YaXTOMGkpyl0GIUHpQLEYveKN+qBIfllwUAMfTT+dr0=,iv:PPvkcmYLO3/4ad7HESa/SjElRzlp0bRINMzud9AK4CA=,tag:wExRxRTJd963InpUXeML6w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
