---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization
namespace: default
resources:
  - ./helmrelease.yaml
generatorOptions:
  disableNameSuffixHash: true
labels:
  - pairs:
      app.kubernetes.io/name: homebridge
      app.kubernetes.io/instance: homebridge
      app.kubernetes.io/part-of: homebridge