---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - ./helmrelease.yaml
  - ./helmrelease2.yaml
labels:
  - pairs:
      app.kubernetes.io/name: nfs-subdir-external-provisioner
      app.kubernetes.io/instance: nfs-subdir-external-provisioner