---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    domain: kirstein.me
    controller:
      type: statefulset
    image:
      repository: ghcr.io/authelia/authelia
      tag: 4.38.10
    args: ["--config", "/etc/authelia/config.yaml"]
    service:
      main:
        ports:
          http:
            port: &port 80
          metrics:
            enabled: true
            port: 8080
    ingress:
      main:
        enabled: true
        ingressClassName: "external-ingress"
        annotations:
          external-dns.alpha.kubernetes.io/target: "home.kirstein.me"
        hosts:
          - host: &host auth.kirstein.me
            paths:
              - path: /
        tls:
          - secretName: authelia-tls-certificate
            hosts:
              - *host
    env:
    - name: TZ
      value: Europe/Berlin
    envFrom:
      - secretRef:
          name: authelia-secret
    enableServiceLinks: false
    resources:
      requests:
        cpu: "0.25"
        memory: 250Mi
      limits:
        memory: 250Mi
    rbac:
      enabled: true
  # secret:
  #   existingSecret: authelia-secrets
    persistence:
      config:
        enabled: true
        type: configMap
        name: authelia-config
        subPath: config.yaml
        mountPath: /etc/authelia/config.yaml
        readOnly: false
      data:
        enabled: true
        mountPath: /config
        storageClass:  nfs-client
        accessMode: ReadWriteOnce
        size: 1Gi