---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./authelia-secret.sops.yaml
  - ./configmap.yaml
  - ./helmrelease.yaml
labels:
  - pairs:
      app.kubernetes.io/name: authelia
      app.kubernetes.io/instance: authelia
      app.kubernetes.io/part-of: authelia