---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: victoria-metrics-stack
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      version: 0.14.17
      sourceRef:
        kind: HelmRepository
        name: victoriametrics
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: "victoria-metrics"
    defaultRules:
      create: false
    grafana:
      enabled: false
    alertmanager:
      enabled: false
    vmsingle:
      ingress:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/hostname: vm.nas01.kirstein.me
          kubernetes.io/ingress.class: internal-ingress
        hosts: 
          - "vm.nas01.kirstein.me"
      storage:
        storageClassName: nfs-client
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
