---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: victoria-metrics-stack
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      version: 0.24.4
      sourceRef:
        kind: HelmRepository
        name: victoriametrics
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: "victoria-metrics"
    defaultRules:
      rules:
        etcd: false
        kubeApiserver: false
        kubeApiserverAvailability: false
        kubeApiserverBurnrate: false
        kubeApiserverSlos: false
        kubelet: false
        kubeScheduler: false
    grafana:
      enabled: false
    kubelet:
      enabled: false
    kubeApiServer:
      enabled: false
    kubeControllerManager:
      enabled: false
    kubeEtcd:
      enabled: false
    kubeScheduler:
      enabled: false
    alertmanager:
      ingress:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/hostname: alertmanager.nas01.kirstein.me
        ingressClassName: internal-ingress
        hosts:
          - "alertmanager.nas01.kirstein.me"
      config:
        global:
          resolve_timeout: 5m
        receivers:
          - name: heartbeat
            webhook_configs:
              - url: "https://push.statuscake.com/${SECRET_ALERTMANAGER_STATUSCAKE_URL}"
                send_resolved: true
          - name: "null"
        route:
          group_by: ["alertname", "job"]
          group_wait: 45s
          group_interval: 10m
          repeat_interval: 12h
          receiver: "null"
          routes:
            - receiver: heartbeat
              group_wait: 0s
              group_interval: 2m
              repeat_interval: 2m
              matchers:
                - alertname =~ "Watchdog"
    vmsingle:
      spec:
        retentionPeriod: 2y
        storage:
          storageClassName: nfs-client
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi
      ingress:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/hostname: vm.nas01.kirstein.me
        ingressClassName: internal-ingress
        hosts: 
          - "vm.nas01.kirstein.me"
    victoria-metrics-operator:
      operator:
        disable_prometheus_converter: false