---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta2
kind: Kustomization
namespace: monitoring
resources:
  - ./helmrelease.yaml
labels:
  - pairs:
      app.kubernetes.io/name: victoria-metrics-stack
      app.kubernetes.io/instance: victoria-metrics-stack