{
 "title": "Solar Übersicht",
 "time": { "from": "now/d", "to": "now" },
 "panels": [
  {
   "title": "Aktuelle Leistung",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ahoy_solar_P_AC_watt", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Gesamtertrag",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ahoy_solar_YieldTotal_kilowattHours{channel=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heutiger Ertrag",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ahoy_solar_YieldDay_wattHours{channel=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Leistung",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "targets": [
    { "expr": "ahoy_solar_P_AC_watt", "legendFormat": "__auto" },
    { "target": [ "sun_altitude" ] }
   ]
  },
  {
   "title": "Einstrahlung",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "ahoy_solar_Irradiation_ratio{channel=\"Right\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by (__name__) (ahoy_solar_P_AC_watt)",
     "legendFormat": "__auto"
    },
    { "target": [ "sun_altitude" ] }
   ]
  }
 ]
}