apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gameserver
resources:
# - allocation.yaml
- cm.yaml
- fleet.yaml
labels:
  - pairs:
      app.kubernetes.io/name: factorio
      app.kubernetes.io/instance: factorio
      app.kubernetes.io/part-of: factorio